In [3]:
import numpy as np

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
from sklearn import cluster



In [4]:
df =pd.read_csv('Heart_Disease_Prediction.csv', delimiter = ',')

In [5]:
df

Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0     70    1                4  130          322             0            2   
1     67    0                3  115          564             0            2   
2     57    1                2  124          261             0            0   
3     64    1                4  128          263             0            0   
4     74    0                2  120          269             0            2   
..   ...  ...              ...  ...          ...           ...          ...   
265   52    1                3  172          199             1            0   
266   44    1                2  120          263             0            0   
267   56    0                2  140          294             0            2   
268   57    1                4  140          192             0            0   
269   67    1                4  160          286             0            2   

     Max HR  Exercise angina  ST depression  Slope of ST  \
0       109                0            2.4            2   
1       160                0            1.6            2   
2       141                0            0.3            1   
3       105                1            0.2            2   
4       121                1            0.2            1   
..      ...              ...            ...          ...   
265     162                0            0.5            1   
266     173                0            0.0            1   
267     153                0            1.3            2   
268     148                0            0.4            2   
269     108                1            1.5            2   

     Number of vessels fluro  Thallium Heart Disease  
0                          3         3      Presence  
1                          0         7       Absence  
2                          0         7      Presence  
3                          1         7       Absence  
4                          1         3       Absence  
..                       ...       ...           ...  
265                        0         7       Absence  
266                        0         7       Absence  
267                        0         3       Absence  
268                        0         6       Absence  
269                        3         3      Presence  

[270 rows x 14 columns]

In [6]:
feature_columns =['Age','Sex','Chest pain type', 'BP', 'Cholesterol','FBS over 120','EKG results', 'Max HR','Exercise angina','ST depression','Slope of ST','Number of vessels fluro','Thallium']
feature_columns


['Age',
 'Sex',
 'Chest pain type',
 'BP',
 'Cholesterol',
 'FBS over 120',
 'EKG results',
 'Max HR',
 'Exercise angina',
 'ST depression',
 'Slope of ST',
 'Number of vessels fluro',
 'Thallium']

In [7]:
df.groupby('Heart Disease').size()

Heart Disease
Absence     150
Presence    120
dtype: int64

In [8]:
X = df[feature_columns].values
y_barra = df['Heart Disease']
y_barra = y_barra.replace('Presence', 1)
y_barra = y_barra.replace('Absence', 0)
df['Heart Disease'] = y_barra
y = df['Heart Disease']


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

In [11]:
classifier = KNeighborsClassifier(n_neighbors=3)

In [12]:
classifier.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [13]:
y_pred = classifier.predict(X)

In [14]:
cm = confusion_matrix(y,y_pred)
cm

array([[124,  26],
       [ 31,  89]], dtype=int64)

In [15]:
accuracy = accuracy_score(y, y_pred)*100
print('Accuracy of our model is equal ' + str(round(accuracy, 2)) + ' %.')

Accuracy of our model is equal 78.89 %.


In [16]:
k_list = list(range(2,20,1))
cv_scores = []

In [17]:
for k in k_list:
  classifier = KNeighborsClassifier(n_neighbors=k)
  classifier.fit(X, y)
  y_pred = classifier.predict(X)
  accuracy = accuracy_score(y, y_pred)*100
  print (k,accuracy)

2 77.03703703703704
3 78.88888888888889
4 77.4074074074074
5 76.66666666666667
6 74.44444444444444
7 75.92592592592592
8 73.70370370370371
9 73.33333333333333
10 72.5925925925926
11 70.37037037037037
12 71.48148148148148
13 71.11111111111111
14 70.37037037037037
15 69.25925925925925
16 67.77777777777779
17 67.03703703703704
18 68.88888888888889
19 70.37037037037037


Tentativa 2

In [18]:
feature_columns =[ 'BP', 'Cholesterol', 'Max HR','ST depression','Slope of ST']
feature_columns

['BP', 'Cholesterol', 'Max HR', 'ST depression', 'Slope of ST']

In [19]:
df.groupby('Heart Disease').size()

Heart Disease
0    150
1    120
dtype: int64

In [20]:
X = df[feature_columns].values
y = df['Heart Disease'].values

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [22]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

In [23]:
classifier = KNeighborsClassifier(n_neighbors=3)

In [24]:
classifier.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [25]:
y_pred = classifier.predict(X)

In [26]:
cm = confusion_matrix(y,y_pred)
cm

array([[126,  24],
       [ 27,  93]], dtype=int64)

In [27]:
accuracy = accuracy_score(y, y_pred)*100
print('Accuracy of our model is equal ' + str(round(accuracy, 2)) + ' %.')

Accuracy of our model is equal 81.11 %.


In [28]:
k_list = list(range(2,20,1))
cv_scores = []

In [29]:
for k in k_list:
  classifier = KNeighborsClassifier(n_neighbors=k)
  classifier.fit(X, y)
  y_pred = classifier.predict(X)
  accuracy = accuracy_score(y, y_pred)*100
  print (k,accuracy)

2 80.0
3 81.11111111111111
4 74.81481481481481
5 74.44444444444444
6 73.33333333333333
7 72.5925925925926
8 70.37037037037037
9 69.62962962962963
10 68.51851851851852
11 69.62962962962963
12 69.25925925925925
13 70.74074074074073
14 70.74074074074073
15 70.0
16 69.25925925925925
17 68.51851851851852
18 70.0
19 69.62962962962963


Tentativa 3

In [30]:
feature_columns =[ 'Cholesterol']
feature_columns

['Cholesterol']

In [31]:
df.groupby('Heart Disease').size()

Heart Disease
0    150
1    120
dtype: int64

In [32]:
X = df[feature_columns].values
y = df['Heart Disease'].values

In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [34]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

In [35]:
classifier = KNeighborsClassifier(n_neighbors=3)

In [36]:
classifier.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [37]:
y_pred = classifier.predict(X)

In [38]:
cm = confusion_matrix(y,y_pred)
cm

array([[118,  32],
       [ 31,  89]], dtype=int64)

In [39]:
accuracy = accuracy_score(y, y_pred)*100
print('Accuracy of our model is equal ' + str(round(accuracy, 2)) + ' %.')

Accuracy of our model is equal 76.67 %.


In [40]:
k_list = list(range(2,20,1))
cv_scores = []

In [41]:
for k in k_list:
  classifier = KNeighborsClassifier(n_neighbors=k)
  classifier.fit(X, y)
  y_pred = classifier.predict(X)
  accuracy = accuracy_score(y, y_pred)*100
  print (k,accuracy)

2 75.92592592592592
3 76.66666666666667
4 72.22222222222221
5 74.44444444444444
6 71.48148148148148
7 71.85185185185186
8 68.51851851851852
9 67.77777777777779
10 66.66666666666666
11 65.55555555555556
12 64.44444444444444
13 65.55555555555556
14 64.07407407407408
15 62.59259259259259
16 62.59259259259259
17 62.96296296296296
18 62.59259259259259
19 60.74074074074074
